name: news
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1  
  timeago: ^3.6.1
  flutter_local_notifications: ^17.0.0
  flutter_bloc: ^8.1.5
  # provider: ^6.1.1
  # flutter_localizations:
  #   sdk: flutter
  # intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:  
  uses-material-design: true

  assets:
    - assets/images/